/**
 * The schemas in this directory are designed to be simpler versions (hence why some are commented out)
 * Of the AI SDK ModelMessage (https://ai-sdk.dev/docs/reference/ai-sdk-core/model-message) Types,
 * and to be compatible with the streamText and generateText functions.
 *
 * Use these inferred types to format messages going TO models.
 */

import type {
  AssistantModelMessage as SdkAssistantModelMessage,
  ModelMessage as SdkModelMessage,
  SystemModelMessage as SdkSystemModelMessage,
  ToolModelMessage as SdkToolModelMessage,
  UserModelMessage as SdkUserModelMessage,
} from "ai";
import { z } from "zod";

// --- Base Content Schemas ---

/**
 * A schema for data content that can be represented in multiple ways.
 * Used for images and files.
 */
const hankweaveDataContentSchema = z.union([
  z.string().describe("Base64-encoded string"),
  z.instanceof(Uint8Array),
  z.instanceof(ArrayBuffer),
  z.instanceof(Buffer), // For Node.js environments
]);

/**
 * JSON value schema compatible with the AI SDK JSONValue type.
 * Allows null, primitive types, arrays and objects with string keys.
 */
export type JsonValue = null | string | number | boolean | { [k: string]: JsonValue } | JsonValue[];
export const jsonValueSchema: z.ZodType<JsonValue> = z.lazy(() =>
  z.union([
    z.null(),
    z.string(),
    z.number(),
    z.boolean(),
    z.array(jsonValueSchema),
    z.record(jsonValueSchema),
  ]),
);

/**
 * Provider-options schema matching AI SDK v5's `SharedV2ProviderOptions`:
 * `Record<string, Record<string, JSONValue>>`.
 *
 * Two-level shape: outer keyed by provider id (e.g. "anthropic"), inner keyed
 * by option name (e.g. "cacheControl"), values JSON-serialisable.
 */
export const providerOptionsSchema = z.record(z.string(), z.record(z.string(), jsonValueSchema));
export type ProviderOptionsValue = z.infer<typeof providerOptionsSchema>;

/**
 * Tool result "content" value parts (used when output.type === 'content').
 * Aligns with LanguageModelV2ToolResultOutput content parts.
 */
const hankweaveToolResultContentValueSchema = z.array(
  z.discriminatedUnion("type", [
    z.object({ type: z.literal("text"), text: z.string() }).strict(),
    z.object({ type: z.literal("media"), data: z.string(), mediaType: z.string() }).strict(),
  ]),
);

/**
 * Output schema for tool results, aligned with LanguageModelV2ToolResultOutput.
 */
const hankweaveToolResultOutputSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("text"), value: z.string() }).strict(),
  z.object({ type: z.literal("json"), value: jsonValueSchema }).strict(),
  z.object({ type: z.literal("error-text"), value: z.string() }).strict(),
  z.object({ type: z.literal("error-json"), value: jsonValueSchema }).strict(),
  z.object({ type: z.literal("content"), value: hankweaveToolResultContentValueSchema }).strict(),
]);

// --- ModelMessage Part Schemas ---

/**
 * Represents a text part of a message.
 */
export const hankweaveTextPartSchema = z
  .object({
    type: z.literal("text"),
    text: z.string(),
    providerOptions: providerOptionsSchema
      .optional()
      .describe(
        "Provider-specific options for this text part (e.g. anthropic cacheControl). Two-level shape: { <provider>: { <option>: <value> } }.",
      ),
  })
  .strict();

/**
 * Represents an image part in a user message.
 */
export const hankweaveImagePartSchema = z
  .object({
    type: z.literal("image"),
    image: z.union([hankweaveDataContentSchema, z.instanceof(URL)]),
    mediaType: z.string().optional(),
  })
  .strict();

/**
 * Represents a file part in a user or assistant message.
 */
export const hankweaveFilePartSchema = z
  .object({
    type: z.literal("file"),
    data: z.union([hankweaveDataContentSchema, z.instanceof(URL)]),
    mediaType: z.string(),
    filename: z.string().optional(),
  })
  .strict();

/**
 * Represents a tool call generated by the model.
 */
export const hankweaveToolCallPartSchema = z
  .object({
    type: z.literal("tool-call"),
    toolCallId: z.string(),
    toolName: z.string(),
    input: z.record(jsonValueSchema).describe("Arguments for the tool call"),
  })
  .strict();

/**
 * Represents the multi-part content of a tool result.
 */
const hankweaveToolResultContentSchema = hankweaveToolResultContentValueSchema;

/**
 * Represents the result of a tool's execution.
 */
export const hankweaveToolResultPartSchema = z
  .object({
    type: z.literal("tool-result"),
    toolCallId: z.string(),
    toolName: z.string(),
    output: hankweaveToolResultOutputSchema,
    experimental_content: hankweaveToolResultContentSchema.optional(),
    isError: z.boolean().optional(),
  })
  .strict();

// --- Full Message Schemas ---

/**
 * A system message for setting the model's behavior.
 */
export const hankweaveSystemModelMessageSchema = z
  .object({
    role: z.literal("system"),
    content: z.string(),
  })
  .strict();

/**
 * A user message, representing input from the end-user.
 */
export const hankweaveUserModelMessageSchema = z
  .object({
    role: z.literal("user"),
    content: z.union([
      z.string(),
      z.array(
        z.union([hankweaveTextPartSchema, hankweaveImagePartSchema, hankweaveFilePartSchema]),
      ),
    ]),
  })
  .strict();

/**
 * An assistant message, representing the response from the model.
 */
export const hankweaveAssistantModelMessageSchema = z
  .object({
    role: z.literal("assistant"),
    content: z.union([
      z.string(),
      z.array(z.union([hankweaveTextPartSchema, hankweaveToolCallPartSchema])),
    ]),
  })
  .strict();

/**
 * A tool message, providing the results of tool calls back to the model.
 */
export const hankweaveToolModelMessageSchema = z
  .object({
    role: z.literal("tool"),
    content: z.array(hankweaveToolResultPartSchema),
  })
  .strict();

// --- The All-Encompassing ModelMessage Schema ---

/**
 * The primary `HankweaveModelMessage` schema.
 * It's a discriminated union of all possible message types, which is the most
 * efficient and type-safe way to validate objects with a shared `role` key.
 */
export const hankweaveModelMessageSchema = z.discriminatedUnion("role", [
  hankweaveSystemModelMessageSchema,
  hankweaveUserModelMessageSchema,
  hankweaveAssistantModelMessageSchema,
  hankweaveToolModelMessageSchema,
]);

// --- EXPORTED TYPES ---

export type HankweaveModelMessage = z.infer<typeof hankweaveModelMessageSchema>;
export type HankweaveSystemModelMessage = z.infer<typeof hankweaveSystemModelMessageSchema>;
export type HankweaveUserModelMessage = z.infer<typeof hankweaveUserModelMessageSchema>;
export type HankweaveAssistantModelMessage = z.infer<typeof hankweaveAssistantModelMessageSchema>;
export type HankweaveToolModelMessage = z.infer<typeof hankweaveToolModelMessageSchema>;

// --- BUILD-TIME TYPE VALIDATION ---
// This section ensures that our Zod schemas remain compatible with the official
// types from the `ai` SDK. It checks that our defined types are valid "subsets"
// of the SDK's types. If the `ai` package is updated with breaking changes,
// running `bun tc` will cause a compile-time error
// in this file, alerting us to update our schemas.

/**
 * A helper function for static type assertions.
 * It checks if HankweaveType can be assigned to SdkType (i.e., is a valid subset).
 * This function has no runtime effect; its purpose is purely for static analysis.
 */
const assertHankweaveIsSubsetOfSdk = <SdkType, _HankweaveType extends SdkType>() => {};

// Check 1: Validate our main discriminated union against the SDK's.
assertHankweaveIsSubsetOfSdk<SdkModelMessage, HankweaveModelMessage>();

// Check 2: Validate each specific message type for more granular error reporting.
assertHankweaveIsSubsetOfSdk<SdkSystemModelMessage, HankweaveSystemModelMessage>();
assertHankweaveIsSubsetOfSdk<SdkUserModelMessage, HankweaveUserModelMessage>();
assertHankweaveIsSubsetOfSdk<SdkAssistantModelMessage, HankweaveAssistantModelMessage>();
assertHankweaveIsSubsetOfSdk<SdkToolModelMessage, HankweaveToolModelMessage>();
